# This is a sample docker compose file. When you're ready to deploy,
# copy and rename it to compose.yml (which is not under version
# control). You can then safely tailor it and not run into merge
# conflicts.
services:
  familytree:
    # The generated image and associated container are both called
    # "familytree". You can choose any name you wish.
    image: familytree:latest
    container_name: familytree
    restart: unless-stopped
    # Map ports as desired. The port internal to the running container
    # (80) must remain unchanged. You can choose any external port you
    # wish
    ports:
      - 80:80
    stdin_open: true
    tty: true
# I'm running a custom external nextwork, but this part is optional
networks:
  default:
    name: mynet
    external: true
